import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-background">
      <Navbar className="mb-8"/>
        {children}
      </body>
    </html>
  );
}
