import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";
import ClientOnlyAudioPlayer from "@/components/clientOnlyAudioPlayer"; // Gebruik de client-only component

export const metadata: Metadata = {
  title: "Nastro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg" />
<link rel="shortcut icon" href="/favicon/favicon.ico" />
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
<link rel="manifest" href="/favicon/site.webmanifest" />
      <body className="bg-background">
        <Navbar className="mb-8" />
        {children}
        <ClientOnlyAudioPlayer/> {/* Voeg de Client Component hier toe */}
        <Footer/>
      </body>
    </html>
  );
}
