import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import "./globals.css";
import ClientOnlyAudioPlayer from "@/components/clientOnlyAudioPlayer"; // Gebruik de client-only component

export const metadata: Metadata = {
  title: "Nastro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-background">
        <Navbar className="mb-8" />
       
        {children}
        <ClientOnlyAudioPlayer/> {/* Voeg de Client Component hier toe */}
      </body>
    </html>
  );
}
